name: sddl_sdk
description: A Flutter SDK for working with SDDL deep links and attribution.
version: 0.0.7
homepage: https://sddl.me

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uni_links: ^0.5.1
  http: ">=0.13.6 <2.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
