name: sddl_sdk
description: A Flutter SDK for working with SDDL deep links and attribution.
version: 0.1.4
homepage: https://sddl.me

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.simplelink.sddl_referrer
        pluginClass: SddlReferrerPlugin
      ios:
        pluginClass: SddlReferrerPlugin

dependencies:
  flutter:
    sdk: flutter
  app_links: ^6.0.0
  http: ">=0.13.6 <2.0.0"
  package_info_plus: ^8.3.1
  flutter_timezone: ^4.1.1
  shared_preferences: ^2.2.3
  device_info_plus: ^10.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
